### ISSUE TITLE
Overlap Months Name

### ISSUE THREAD

**Issue by sanjay270899** [haripo/react-github-contribution-calendar#16]
Any way to fix this overlap of `Dec` and `Jan` month name?

![image](https://user-images.githubusercontent.com/43892590/120160566-02615600-c214-11eb-8521-e9cf69d7a42b.png)

**Comment by sanjay270899** [comment]
![image](https://user-images.githubusercontent.com/43892590/120177057-9ab40680-c225-11eb-98ba-c6c5ac88560d.png)

https://github.com/haripo/react-github-contribution-calendar/blob/e655ddb97eda766b38579df29248c405a547697e/src/index.tsx#L34

One quick fix I found is to change the value of columns from 53 to 52.

**Comment by haripo** [comment]
Fixed in 2.1.0. Thanks you for reporting!
